const Anthropic = require('@anthropic-ai/sdk');
const fs = require('fs');
const path = require('path');

// =============================================================================
// CONFIGURATION
// =============================================================================

const anthropic = new Anthropic({
    apiKey: process.env.ANTHROPIC_API_KEY,
});

const FILES_TO_ANALYZE = [
    { path: 'main.js', description: 'Main Electron process' },
    { path: 'renderer.js', description: 'Renderer process (UI logic)' }
];

const PROJECT_NAME = 'LudicoAI_V2';
const PROJECT_DESCRIPTION = 'Video transcription tool with AI-powered subtitles using Whisper API and Video.js';

// =============================================================================
// READ FILES
// =============================================================================

function readProjectFiles() {
    const filesContent = FILES_TO_ANALYZE.map(file => {
        const fullPath = path.join(process.cwd(), file.path);
        
        if (!fs.existsSync(fullPath)) {
            console.warn(`⚠️ Warning: ${file.path} not found`);
            return null;
        }
        
        const content = fs.readFileSync(fullPath, 'utf8');
        console.log(`✅ Read ${file.path} (${content.length} chars)`);
        
        return {
            path: file.path,
            description: file.description,
            content: content
        };
    }).filter(Boolean);
    
    return filesContent;
}

// =============================================================================
// GENERATE README WITH AI
// =============================================================================

async function generateReadme(filesContent) {
    console.log('🤖 Calling Claude API to generate README...');
    
    // Build file context for Claude
    const fileContext = filesContent.map(file => 
        `### ${file.path} (${file.description})
\`\`\`javascript
${file.content}
\`\`\`
`
    ).join('\n\n');
    
    const prompt = `You are a technical documentation expert. Analyze the following Electron application code and generate a comprehensive, professional README.md file.

# Project Information
- Name: ${PROJECT_NAME}
- Description: ${PROJECT_DESCRIPTION}

# Code Files to Analyze:

${fileContext}

# Instructions:

Generate a complete README.md that includes:

1. **Project Title & Description** - Clear, concise overview
2. **Key Features** - Bullet points of main capabilities (from code analysis)
3. **Architecture Overview** - Brief explanation of how it works
4. **Prerequisites** - What users need installed
5. **Installation** - Step-by-step setup instructions
6. **Usage** - How to run and use the application
7. **Configuration** - Environment variables and settings (especially API keys)
8. **Features Breakdown** - Detailed explanation of key features with examples
9. **Technology Stack** - List of technologies used
10. **File Structure** - Overview of main files
11. **Troubleshooting** - Common issues and solutions
12. **Future Enhancements** - Potential improvements mentioned in code
13. **Contributing** - How to contribute
14. **License** - License information

# Style Guidelines:
- Use emojis strategically for visual appeal (🚀, 📦, ⚙️, etc.)
- Include code examples where relevant
- Be professional but approachable
- Use proper Markdown formatting
- Include badges for tech stack if appropriate
- Make it visually scannable with good hierarchy
- Focus on what the code ACTUALLY does (don't hallucinate features)
- Highlight the caching system and API credit saving features
- Explain the chunking mechanism for long videos
- Note the .env configuration for API keys

Generate the complete README.md now (output only the markdown, no extra commentary):`;

    try {
        const message = await anthropic.messages.create({
            model: 'claude-sonnet-4-20250514',
            max_tokens: 4000,
            messages: [{
                role: 'user',
                content: prompt
            }]
        });
        
        const readme = message.content[0].text;
        console.log('✅ README generated successfully!');
        console.log(`📄 Length: ${readme.length} characters`);
        
        return readme;
        
    } catch (error) {
        console.error('❌ Error calling Claude API:', error);
        throw error;
    }
}

// =============================================================================
// SAVE README
// =============================================================================

function saveReadme(content) {
    const readmePath = path.join(process.cwd(), 'README.md');
    
    // Add generation timestamp footer
    const timestamp = new Date().toISOString();
    const footer = `\n\n---\n\n*🤖 This README was automatically generated by AI on ${timestamp}*\n`;
    
    const finalContent = content + footer;
    
    fs.writeFileSync(readmePath, finalContent, 'utf8');
    console.log('✅ README.md saved successfully!');
}

// =============================================================================
// MAIN EXECUTION
// =============================================================================

async function main() {
    console.log('🚀 Starting README generation...\n');
    
    try {
        // Check API key
        if (!process.env.ANTHROPIC_API_KEY) {
            throw new Error('❌ ANTHROPIC_API_KEY environment variable not set!');
        }
        
        // Read files
        console.log('📂 Reading project files...');
        const filesContent = readProjectFiles();
        
        if (filesContent.length === 0) {
            throw new Error('❌ No files found to analyze!');
        }
        
        console.log(`✅ Found ${filesContent.length} files to analyze\n`);
        
        // Generate README
        const readme = await generateReadme(filesContent);
        
        // Save README
        saveReadme(readme);
        
        console.log('\n✅ README generation complete! 🎉');
        
    } catch (error) {
        console.error('\n❌ Error:', error.message);
        process.exit(1);
    }
}

// Run
main();